# Generated by Django 5.1.1 on 2024-11-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_prompt', models.TextField()),
                ('gpt_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='FineTuningQuery',
        ),
    ]
