# Generated by Django 5.1.1 on 2024-12-14 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_queries', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Request Count',
                'verbose_name_plural': 'User Request Counts',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
