from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class GPUInfo:
    name: str
    memory_mib: int
    driver_version: str
    compute_cap: str | None = None


@dataclass(slots=True)
class HardwareSnapshot:
    cpu_cores: int
    logical_processors: int
    memory_gib: float
    wsl_present: bool
    docker_desktop_wsl2: bool
    gpu_visible_in_wsl: bool
    gpus: list[GPUInfo]


@dataclass(slots=True)
class RuntimePlan:
    profile: str
    enable_gpu: bool
    enable_vllm: bool
    stt_device: str
    stt_compute_type: str
    ollama_acceleration: str
    model_concurrency: int
    chunk_ms: int
    notes: list[str]

    def to_env(self) -> dict[str, str]:
        return {
            "RUNTIME_PROFILE": self.profile,
            "ENABLE_GPU": str(self.enable_gpu).lower(),
            "ENABLE_VLLM": str(self.enable_vllm).lower(),
            "STT_DEVICE": self.stt_device,
            "STT_COMPUTE_TYPE": self.stt_compute_type,
            "OLLAMA_ACCELERATION": self.ollama_acceleration,
            "MODEL_CONCURRENCY": str(self.model_concurrency),
            "STT_CHUNK_MS": str(self.chunk_ms),
        }


def _best_nvidia_gpu(snapshot: HardwareSnapshot) -> GPUInfo | None:
    nvidia = [gpu for gpu in snapshot.gpus if "nvidia" in gpu.name.lower() or "quadro" in gpu.name.lower()]
    return max(nvidia, key=lambda gpu: gpu.memory_mib, default=None)


def select_runtime_plan(snapshot: HardwareSnapshot) -> RuntimePlan:
    gpu = _best_nvidia_gpu(snapshot)
    if not gpu:
        return RuntimePlan(
            profile="local-cpu",
            enable_gpu=False,
            enable_vllm=False,
            stt_device="cpu",
            stt_compute_type="int8",
            ollama_acceleration="cpu",
            model_concurrency=2,
            chunk_ms=350,
            notes=[
                "No NVIDIA GPU detected. All inference services default to CPU mode.",
                "vLLM stays disabled because the local-first target is CPU only.",
            ],
        )

    compute_cap = float(gpu.compute_cap or "0")
    low_vram = gpu.memory_mib < 6144
    wsl_gpu_ready = snapshot.wsl_present and snapshot.docker_desktop_wsl2 and snapshot.gpu_visible_in_wsl

    if wsl_gpu_ready and not low_vram and compute_cap >= 7.0:
        return RuntimePlan(
            profile="local-nvidia-wsl2",
            enable_gpu=True,
            enable_vllm=True,
            stt_device="cuda",
            stt_compute_type="float16",
            ollama_acceleration="gpu",
            model_concurrency=2,
            chunk_ms=200,
            notes=[
                "NVIDIA GPU is visible from Docker Desktop WSL2.",
                "VRAM and compute capability are sufficient for an optional tiny-model vLLM path.",
            ],
        )

    return RuntimePlan(
        profile="local-hybrid",
        enable_gpu=True,
        enable_vllm=False,
        stt_device="cuda" if wsl_gpu_ready else "cpu",
        stt_compute_type="int8_float16" if wsl_gpu_ready else "int8",
        ollama_acceleration="gpu" if wsl_gpu_ready else "cpu",
        model_concurrency=1,
        chunk_ms=250,
        notes=[
            "GPU acceleration is available for lightweight local services.",
            "vLLM is disabled because the GPU is older or memory-constrained for a safe default local setup.",
        ],
    )


def env_file_text(plan: RuntimePlan, snapshot: HardwareSnapshot) -> str:
    lines = [
        "# Generated by scripts/detect_hardware.*",
        *[f"{key}={value}" for key, value in plan.to_env().items()],
        f"CPU_CORES={snapshot.cpu_cores}",
        f"LOGICAL_PROCESSORS={snapshot.logical_processors}",
        f"MEMORY_GIB={snapshot.memory_gib:.1f}",
        f"GPU_VISIBLE_IN_WSL={str(snapshot.gpu_visible_in_wsl).lower()}",
    ]
    if snapshot.gpus:
        lines.append(f'PRIMARY_GPU="{snapshot.gpus[0].name}"')
    return "\n".join(lines) + "\n"


def report_markdown(plan: RuntimePlan, snapshot: HardwareSnapshot) -> str:
    gpu_lines = (
        "\n".join(
            f"- {gpu.name} | {gpu.memory_mib} MiB | driver {gpu.driver_version} | compute {gpu.compute_cap or 'n/a'}"
            for gpu in snapshot.gpus
        )
        or "- none"
    )
    notes = "\n".join(f"- {note}" for note in plan.notes)
    return f"""# Hardware Report

## Detected Host
- CPU cores: {snapshot.cpu_cores}
- Logical processors: {snapshot.logical_processors}
- Memory: {snapshot.memory_gib:.1f} GiB
- WSL present: {str(snapshot.wsl_present).lower()}
- Docker Desktop WSL2 backend: {str(snapshot.docker_desktop_wsl2).lower()}
- GPU visible in WSL: {str(snapshot.gpu_visible_in_wsl).lower()}

## GPUs
{gpu_lines}

## Selected Runtime Profile
- Profile: `{plan.profile}`
- GPU enabled: `{str(plan.enable_gpu).lower()}`
- vLLM enabled: `{str(plan.enable_vllm).lower()}`
- faster-whisper device: `{plan.stt_device}`
- faster-whisper compute type: `{plan.stt_compute_type}`
- Ollama acceleration: `{plan.ollama_acceleration}`
- Model concurrency: `{plan.model_concurrency}`
- Audio chunk size: `{plan.chunk_ms}ms`

## Notes
{notes}
"""


def parse_snapshot(payload: dict[str, Any]) -> HardwareSnapshot:
    gpus = [
        GPUInfo(
            name=item["name"],
            memory_mib=int(item.get("memory_mib", 0)),
            driver_version=str(item.get("driver_version", "unknown")),
            compute_cap=item.get("compute_cap"),
        )
        for item in payload.get("gpus", [])
    ]
    return HardwareSnapshot(
        cpu_cores=int(payload["cpu_cores"]),
        logical_processors=int(payload["logical_processors"]),
        memory_gib=float(payload["memory_gib"]),
        wsl_present=bool(payload["wsl_present"]),
        docker_desktop_wsl2=bool(payload["docker_desktop_wsl2"]),
        gpu_visible_in_wsl=bool(payload["gpu_visible_in_wsl"]),
        gpus=gpus,
    )

